const ESCAPE_ROOM_FILE = "terpeca-2021-round1.txt";
const GOOGLE_MAPS_API_KEY = process.env.REACT_APP_GOOGLE_MAPS_API_KEY;
const GOOGLE_GEOCODING_API_KEY = process.env.REACT_APP_GOOGLE_GEOCODING_API_KEY;

export {
  ESCAPE_ROOM_FILE,
  GOOGLE_MAPS_API_KEY,
  GOOGLE_GEOCODING_API_KEY
}